// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMDCheckSheet.Data;

#nullable disable

namespace SMDCheckSheet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128090020_dbnew")]
    partial class dbnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMDCheckSheet.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.ChangeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckModelId")
                        .HasColumnType("int");

                    b.Property<int>("PQCCheckId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramCheckId")
                        .HasColumnType("int");

                    b.Property<int>("StandardProductId")
                        .HasColumnType("int");

                    b.Property<int>("StandardProductionId")
                        .HasColumnType("int");

                    b.Property<int>("StandardVehicleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeChangeModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckModelId");

                    b.HasIndex("PQCCheckId");

                    b.HasIndex("ProgramCheckId");

                    b.HasIndex("StandardProductionId");

                    b.HasIndex("StandardVehicleId");

                    b.HasIndex("TimeChangeModelId");

                    b.ToTable("ChangeModels");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.CheckModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePCB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FeederCheck")
                        .HasColumnType("datetime2");

                    b.Property<bool>("JIG")
                        .HasColumnType("bit");

                    b.Property<string>("LineChange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OPAccept")
                        .HasColumnType("datetime2");

                    b.Property<string>("PCBver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.Property<bool>("UsedCNcard")
                        .HasColumnType("bit");

                    b.Property<string>("WorkOrder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CheckModels");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.PQCCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecksumConfirm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChecksumReal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndLCR")
                        .HasColumnType("time");

                    b.Property<string>("ICPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCheck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ResultLCR")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartLCR")
                        .HasColumnType("time");

                    b.Property<string>("Turner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PQCChecks");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.ProgramCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MOAIProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MounterProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointMounter")
                        .HasColumnType("int");

                    b.Property<int>("PointSOAI")
                        .HasColumnType("int");

                    b.Property<string>("PrinterProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReflowProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReflowSpeed")
                        .HasColumnType("int");

                    b.Property<string>("SOAIProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPIProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgramChecks");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.StandardProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LabelProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MLS3Closed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumMASK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumMES")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumScanPrinter")
                        .HasColumnType("int");

                    b.Property<int>("NumScanSignMES")
                        .HasColumnType("int");

                    b.Property<string>("UseOnly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StandardProductions");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.StandardVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AOICheck")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AOIQ1")
                        .HasColumnType("bit");

                    b.Property<bool>("MountQ1")
                        .HasColumnType("bit");

                    b.Property<bool>("MountQ2")
                        .HasColumnType("bit");

                    b.Property<string>("NameAOI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PrinterQ1")
                        .HasColumnType("bit");

                    b.Property<int>("PrinterRealDSL")
                        .HasColumnType("int");

                    b.Property<int>("PrinterRealGTAL")
                        .HasColumnType("int");

                    b.Property<int>("PrinterRealTDKC")
                        .HasColumnType("int");

                    b.Property<int>("PrinterRealTDQ")
                        .HasColumnType("int");

                    b.Property<int>("PrinterSpecDSL")
                        .HasColumnType("int");

                    b.Property<int>("PrinterSpecGTAL")
                        .HasColumnType("int");

                    b.Property<int>("PrinterSpecTDKC")
                        .HasColumnType("int");

                    b.Property<int>("PrinterSpecTDQ")
                        .HasColumnType("int");

                    b.Property<int>("ReFlowRealRail")
                        .HasColumnType("int");

                    b.Property<int>("ReFlowSettingRail")
                        .HasColumnType("int");

                    b.Property<bool>("ReflowQ1")
                        .HasColumnType("bit");

                    b.Property<bool>("SPIQ1")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("StandardVehicles");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.TimeChangeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountTime")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("History")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TimeChangeModels");
                });

            modelBuilder.Entity("SMDCheckSheet.Models.ChangeModel", b =>
                {
                    b.HasOne("SMDCheckSheet.Models.CheckModel", "CheckModel")
                        .WithMany()
                        .HasForeignKey("CheckModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMDCheckSheet.Models.PQCCheck", "PQCCheck")
                        .WithMany()
                        .HasForeignKey("PQCCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMDCheckSheet.Models.ProgramCheck", "ProgramCheck")
                        .WithMany()
                        .HasForeignKey("ProgramCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMDCheckSheet.Models.StandardProduction", "StandardProduction")
                        .WithMany()
                        .HasForeignKey("StandardProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMDCheckSheet.Models.StandardVehicle", "StandardVehicle")
                        .WithMany()
                        .HasForeignKey("StandardVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMDCheckSheet.Models.TimeChangeModel", "TimeChangeModel")
                        .WithMany()
                        .HasForeignKey("TimeChangeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckModel");

                    b.Navigation("PQCCheck");

                    b.Navigation("ProgramCheck");

                    b.Navigation("StandardProduction");

                    b.Navigation("StandardVehicle");

                    b.Navigation("TimeChangeModel");
                });
#pragma warning restore 612, 618
        }
    }
}
